"""empty message

Revision ID: 1fb3287dc7f9
Revises: 374af8bfa79b
Create Date: 2025-04-13 12:21:50.489306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fb3287dc7f9'
down_revision: Union[str, None] = '374af8bfa79b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('username', sa.String(), nullable=False))
    op.add_column('chat_messages', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint('chat_messages_sender_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'sender_id')
    op.drop_column('chat_messages', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('time', postgresql.TIME(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('chat_messages', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('chat_messages_sender_id_fkey', 'chat_messages', 'users', ['sender_id'], ['id'])
    op.drop_column('chat_messages', 'timestamp')
    op.drop_column('chat_messages', 'username')
    # ### end Alembic commands ###
